---
- name: Harden IOS XE Devices
  hosts: iosxe
  connection: netconf
  gather_facts: false

  tasks:
    - name: Force SSH Version 2
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <ip>
                  <ssh>
                    <ssh-version>2</ssh-version>
                  </ssh>
                </ip>
              </native>
            </config>

